version: '3.7'

# Define service
services:
  #App backend service
  app-server:
  # Configuration for building the docker image for the backend service
    build:
      context: .  # use an image built from the specified dockerfile in the `twitter-polls-server` directory.
      dockerfile: Dockerfile
    ports:
    - "8085:8085"  # Forward the exposed port 8085 on the container to port 8085 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. start that firs.
    environment: #pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/twitter_polls?serverTimeZone=UTC&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: twitter
      SPRING_DATASOURCE_PASSWORD: twitter
    networks: #Networks to join(Services on the same network can communicate with each other using their name)
      - backend

  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: twitter_polls
      MYSQL_USER: twitter
      MYSQL_PASSWORD: twitter
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  # Volumes
volumes:
  db-data:

  # Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
